name: Publish to Marketplace

on:
  push:
    branches:
    - production

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      bump_success: ${{ false }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install extension
      run: npm install

    # bump version and publish using vsce
    - name: Publish version
      if: startsWith(github.event.head_commit.message, 'v')
      run: npm run deploy ${{github.event.head_commit.message[1:]}} --githubBranch production
      env:
        bump_success: ${{ true }}
    - name: Check bump success # exit
      if: ${{ !bump_success }}
      exit-on-failure: true

    # create tags and push to origin
    - name: Create tag
      uses: actions/create-release@v1
      with:
        tag_name: 'v${{github.event.head_commit.message[1:]}}'
        release_name: 'v${{github.event.head_commit.message[1:]}}'
